### ISSUE TITLE
Burp doesn´t backup files where only the permissions have changed

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#265]
I tested this with Burp 1.3.8 (Debian Wheezy package) and manually installed 1.4.32. Burp v2 wouldn´t continue step 2 so I didn´t examine any further.

Steps to reproduce:
- Make a backup of some files
- chmod +x one_file
- Start a second backup

"one_file" will not be backed up, but IMHO it should be.

**Comment by grke** [comment]
Hello,
See my reply to your other question about symlinks and empty directories on the mailing list, this is the same issue. The ownership is meta data and goes in the manifest file, so the whole file doesn't need to be backed up in this situation. The phase1 scan contains enough information.
The mailing list post was this:


My guess is that you are not using the client for lists/restores/verifies,
and instead are assuming that the pseudo-mirror in the backup directories
on the server side is an actual mirror (as you would get using, for example,
rsync).

Burp stores file data that it has backed up in the server storage
directories.
It doesn't make file system entries there if it does not need to. For
example, an empty file doesn't need a file system entry. It just needs its
meta data entered in the manifest file.
A symlink doesn't need a file system entry on the server side, as it contains
no file data. It just needs its meta data entered in the manifest file.
A directory doesn't need a file system entry if it has no contents. It just
needs its meta data entered in the manifest file.
The same goes for permissions and ownerships. These are meta data that go in
the manifest file.

If you do what Ziirish suggests, you will see that the symlinks are listed.
Use '-a L' instead of '-a l' to get a long list.
To restore, use '-a r' instead of '-a l', and your symlinks and empty
directories
will come back. You might want to restore to a different directory with
the '-d'
option.

**Comment by grke** [comment]
Sorry, I was wrong. I can reproduce the bug. Reopening.

**Comment by grke** [comment]
Fixed in 2.0.15 burp-2 protocol 1. More to come.

**Comment by grke** [comment]
Fixed for the next burp-1 release. More to come.

**Comment by grke** [comment]
Tests added to burp-2 to prevent it breaking again.
Burp-2 protocol 2 seems to have been OK.
Closing.

**Comment by larsen0815** [comment]
Tested, works fine. Thx!
