### ISSUE TITLE
Add option to run a script without automatically passing arguments

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#274]
At the moment, burp automatically passes arguments of its own ('pre', 'reserved2' to 'reserved5') to the script that the user configures via "backup_script_pre". This leads to a problem with automysqlbackup that silently exits without having created SQL dumps. The user has to create a workaround script to be called by burp that in turn calls automysqlbackup without params.

IMHO there will be other use cases where the called script cannot handle the params that burp automatically passes.
An easy workaround is available, but it would be more convenient to simply call the script (and it would be cleaner).

I propose to add these configuration options and would even set it to false by default because I assume that most users don´t need the passed params, so they won´t be surprised when their script fails for no apparent reason.

    backup_script_pre_pass_reserved_args=false/true (default: false)
    backup_script_post_pass_reserved_args=false/true (default: false)
    server_script_pre_pass_reserved_args=false/true (default: false)
    server_script_post_pass_reserved_args=false/true (default: false)

**Comment by grke** [comment]
The default should be true, so that the scripts continue to work as they always have done, and not break when people upgrade.

**Comment by grke** [comment]
I think that the server side scripts 100% need the reserved args, because they need to know which client, what the action was, etc etc.
You missed out client side restore scripts though, so it should be:

backup_script_pre_reserved_args
backup_script_post_reserved_args
restore_script_pre_reserved_args
restore_script_post_reserved_args
plus
backup_script_reserved_args
restore_script_reserved_args
(which set both pre/post for backup/restore)

But then, this all seems like too much.
I think you just need a single config item for all client side scripts:
pass_reserved_args_to_scripts=[0|1] (default to 1)

**Comment by larsen0815** [comment]
Sounds good.

**Comment by grke** [comment]
2.0.17 now has:
backup_script_reserved_args=0|1
restore_script_reserved_args=0|1
Both default to 1 so as not to break existing scripts.
