### ISSUE TITLE
Burp1 is slow with litte files

### ISSUE THREAD

**Issue by francois-he-he** [grke/burp#280]
Hello,
The few tests I did with burp1 shows a slow during phase 2 .
Version 2 is faster but inexplatoible production as too unstable.
Can you tell me what makes Phase 2 as slow with small files ? Is there a solution to increase performance ? Version 1 will she improved?

Kind regards

**Comment by grke** [comment]
Hello,

You can try these to increase performance:
*) Set librsync=0 in burp-server.conf. This will mean that burp will treat changed files as completely new and will not use the librsync algorithm. These saves time on fast networks.
*) set hardlinked_archive=1 in burp-server.conf. This will mean that burp will not generate reverse deltas to save server space across backups.
*) set compression=0 in burp-server.conf. Files will not be compressed.
I am only fixing critical bugs in burp-1.

Burp-2 contains burp-1 functionality. You can set protocol=1 in burp-server.conf. Otherwise, if you are
also using burp-2 clients, it will use protocol 2.
I am unclear on whether you tested burp-2 with protocol 1 or protocol 2.
Burp-2 protocol 1 has improvements over burp-1, as I made some efficiency fixes in the final (server side) backup phases. Any further improvements will be added in burp-2, rather than the old burp-1 code.
Burp-2 protocol 2 is very, very different to protocol 1. I will not explain this here, because I wrote a
whole academic paper about it, along with performance tests against burp-1 and other backup
software. You can read it on my website: http://burp.grke.org/burp2/00contents.html


By the way, I use this github issues list for feature requests and bugs that I will fix.
For questions like yours, they are better on the burp-users mailing list. More people than just me
will see your questions there.
So, I will close this issue. If you want to continue the conversation, please post on the mailing list.

**Comment by francois-he-he** [comment]
OK
Thanks a lot
