### ISSUE TITLE
Increase data available to notify_script

### ISSUE THREAD

**Issue by BobRyanConsulting** [grke/burp#286]
We would like to build a more robust reporting system using the notify_script but the data passed to it on the command line is fairly limited. Currently we're parsing the backup_stats file to get backup size but it would be nice if this, and other info such as failure message could be passed to the script.

**Comment by grke** [comment]
Hello,

The relevant storage directory is passed to the script so that you can read
the details that you want from that storage directory's backup_stats file.

The backup_stats file may contain more than a hundred lines of information. It
is not a good idea to start trying to pass them in as parameters. The file is
deliberately in machine-readable format to facilitate parsing it.


There is no definitive failure message to pass to the script. A low level part
of burp might have an error, log it, return an error code, and the next level
up may log an error too (and so on up the stack).
There may also be an error logged at the low level and the part of burp that
called it may carry on if it thinks it can.
All the messages are put in the log file, and the location of the log file is
given to the notification script.

You are welcome to suggest an alternative code structure that would facilitate
what you want to do, and we can discuss that.

**Comment by grke** [comment]
I will close this issue in about a week's time, if there is nothing more to be said.

**Comment by BobRyanConsulting** [comment]
grke,

Sorry to be a pain but we're still having some problems grabbing data. We've got "working_dir_recovery_method = resume" in our config though by the time the notify script runs and passes the storagedir ie /zraid/burp/myhost.domain.com/current this link points to the last successful backup and there don't appear to be any remnants of the failed backup to parse. 

At what stage in the process is the failed backup directory removed and is this configurable?

**Comment by grke** [comment]
Hello,

If you have 'working_dir_recovery_method=resume', the failed directory is only
removed if the backup was interrupted in phase1.
This happens the next time the client connects after the failure and this is
not configurable.
When the notification script runs, the directory will still be there because
the client is locked out until the current server child process is finished.

If you look at the existing notification script, the base directory is passed
in as the second argument, and the script builds $working and $finishing from
it, which are the paths that you are interested in in the failure case.

See here for more information on 'working', 'finishing' and 'current':
http://burp.grke.org/docs/working_dir.html
