### ISSUE TITLE
Use more standard format for config file

### ISSUE THREAD

**Issue by C-Otto** [grke/burp#289]
Right now, the configuration file does not include a section header (e.g. "[main]"), and options like "keep" or "include" are repeated.

For automated scripts it would be nice to have a standard format, for example the one defined by python's configparser module.

**Comment by grke** [comment]
Hello,

There is not a chance of me changing the current format any time soon, unless there is a very very good reason.

What is wrong with repeating an option like 'include', and how would your preferred standard do it better?

**Comment by C-Otto** [comment]
I understand the troubles of changing the format. Backwards compatibility would be necessary, of course.

The problem with repeated options is that existing libraries for ini/config files treat it as an error. Retrieving a value usually works by specifying the key, which implies the key is unique.

Instead, one could use a single string, separated by commas or spaces.

**Comment by grke** [comment]
Hello,

Your idea of a single string separated by commas or spaces would be OK for something like the 'keep' option (eg, 'keep = 7,4,12'), but consider something like 'exclude'.

The default Windows burp.conf has this:

exclude_regex = ^[A-Z]:/recycler$
exclude_regex = ^[A-Z]:/\$recycle\.bin$
exclude_regex = ^[A-Z]:/pagefile\.sys$
exclude_regex = ^[A-Z]:/swapfile\.sys$
exclude_regex = ^[A-Z]:/hiberfil\.sys$

Which would become this, with the comma scheme:

exclude_regex = ^[A-Z]:/recycler$,^[A-Z]:/\$$recycle\.bin$,^[A-Z]:/pagefile\.sys$,^[A-Z]:/swapfile\.sys$,^[A-Z]:/hiberfil\.sys$

This is much harder to read, and you cannot now specify a comma as part of one of the patterns.
I prefer the existing format.

I don't use it myself, but I believe that puppet is able to support burp config files. For example, take a look here:
https://github.com/naturalis/puppet-burp

Sorry, but I will now close this issue, because I am not going to change the format.

**Comment by C-Otto** [comment]
OK, thank you.
