### ISSUE TITLE
Request -b option to list LAST

### ISSUE THREAD

**Issue by spmetas** [grke/burp#293]
Hello,

when listing files, there is perfect thing that you can list all backups with
-b a
or exact backup with 
-b number
but when making scripting, there would be VERY helpful and reduce steps of getting LAST succesfull backup number to pass it to argument, if there would simple option:
-b l
l - means last.

**Comment by grke** [comment]
This is already a new feature implemented in burp-2.
-b c (for 'current')

**Comment by spmetas** [comment]
Is it possible to backport it to 1.4-master?

**Comment by grke** [comment]
Sorry, but I am being strict about only bug fixes going in 1.4, and new features in 2.0. Otherwise I would never make any forward progress. Thanks for your ideas, I really appreciate you taking the time to make your suggestions for making burp better.

**Comment by spmetas** [comment]
Hello, 
I understand you, and I want to know is it burp2 server backward compatible with 1.4?
Especially storage of backups, is it possible to keep backup history when migrating?
Also if not, would you accept git pull changes in 1.4-master?

**Comment by grke** [comment]
Yes, it is backwards compatible.
For example, my server is 2.0.20, and I have a 1.4.38 client.
If you have 2.0 server and clients, you will need to specify protocol=1 in either the server or client conf file, otherwise it will use protocol=2, which stores backups completely differently.

I want as few changes to 1.4-master as possible, so that I can call it 'stable' and not touch it anymore.
