### ISSUE TITLE
Add include/exclude wildcards.

### ISSUE THREAD

**Issue by basd82** [grke/burp#3]
Add include/exclude wildcards.

**Comment by grke** [comment]
From juodumas:

"include = c:/users/me
include = c:/app
include_regex = ^c:/users/me/.+\.(xls|doc)$|^c:/app
exclude_regex = ^c:/app/.+/bak/$

It would work on files found by include/include_glob directives. This means that include=... or include_glob=... would be required to use include_regex. Should be rather simple to implement and fit a number of use cases. But real per hierarchy rules would still be needed, because complex regexes are too hard on the eyes.

Per my suggestion, include_regex would work exactly like exclude_regex, except negated. It would not include paths described in the regex, but rather filter paths already included with include and include_glob. So it would be as efficient as exclude_regex."



I think this is reasonable, and would finally get rid of this issue #3.

**Comment by grke** [comment]
Thanks, ziirish!
