### ISSUE TITLE
Improve logging when max_children has been reached

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#313]
Using Burp 2.0.20 this is logged when a client tries to connect, but the server already has reached it´s "max_children" setting.

Server:
````
Aug  6 02:38:02 myserver burp[31814]: Too many child processes.
````

Client:
````
2015-08-06 02:38:02: burp[422] SSL connect error
````

I suggest to improve this so the user can see which client was rejected when looking at the server log and the value of "max_children":

    Too many child processes (max_children = $max_children). Rejected client $client.

The client´s log message should explain why the connection could not be established. "SSL error" sounds like something bad happened.

    Server rejected connection as there are too many child processes (max_children = $max_children).

**Comment by larsen0815** [comment]
Probably also applies to "max_status_children".

**Comment by grke** [comment]
The server doesn't yet know the client name at the time that it rejects it.
The idea of max_children is to reduce load. Going through the authentication and reading in the clientconfdir file just to log more detail in a message isn't something that I want to let it do.

To be able to tell the client a specific error, the server would need to do a whole lot of SSL initialisation in order to write back to it. I also don't want to let it do that.

Imagine 1000 clients all trying to connect at once.

**Comment by larsen0815** [comment]
Ok, I understand. Would it be possible to log the IP address of the client only?

**Comment by grke** [comment]
Yes, I will do that.

**Comment by grke** [comment]
Done for the next release of burp-2.
