### ISSUE TITLE
Burp monitor is listening on IPv6 only when using the default status_address

### ISSUE THREAD

**Issue by larsen0815** [grke/burp#315]
I have not configured a value for "status_address" and would suspect the server to listen on all interfaces, but apparently it only listens on the IPv6 one:

````
# netstat -plant | grep 4972
tcp6       0      0 ::1:4972                :::*                    LISTEN      1644/burp
````

IMHO it should listen on both IPv4 and IPv6. The client then should choose what suits best.

**Comment by tokudan** [comment]
It listens on the IPv6 localhost address [::1], so whatever the burp server supports, the client will support as well, as it has to be on the same system.
If you change the listen address to something else, it's up to you to decide.
I'm not sure I understand your problem.

**Comment by larsen0815** [comment]
The client has to be on the same system? I am backing up several clients to one master.

**Comment by tokudan** [comment]
You're looking at the status port used by the monitor, not the ports that clients connect to.
The client port is 4971.

**Comment by larsen0815** [comment]
This ticket is about the monitor, not about backing up clients.

I was referring to the other clients to point out that there are multiple clients that may connect to the monitor, so your statement "...the client will support as well, as it has to be on the same system" doesn´t make any sense to me. I can connect all my clients to the server monitor.

**Comment by grke** [comment]
Status monitor works differently in burp2 and allows non local status clients to connect. Larsen is using burp2.
You can set status_address=0.0.0.0 on the server to get ipv4. It doesn't do both at the same time.

**Comment by larsen0815** [comment]
Ah, sorry. I didn't know this difference to burp1.

It "doesn't" listen or it "cannot"?
Cause I think it would be technically possible, wouldn't it?

**Comment by grke** [comment]
It should be technically possible.
I had a very quick go at trying to do it today, but failed. I won't be able to try again for a while.

If you want to try, the code is in src/server/main.c:init_listen_socket().
It looks like it is trying to do it, but it isn't working for some reason.

The bit that tries to turn off IPV6_V6ONLY should come before bind().

**Comment by larsen0815** [comment]
Sorry, I don't have any C/C++ experience whatsoever.

**Comment by grke** [comment]
I looked at this again. I think that tukodan was absolutely correct in his first reply.


What is happening is that Linux only listens on IPv6 and IPv4 at the same time for the wildcard address ("::").

The burp server main port is ("::") by default, and the status port is localhost ("::1").
So, the main port gets IPv4 and IPv6. The status port only gets IPv6 because "::1" is not the wildcard address. 

I am not going to change the status port from listening to localhost by default, but you may set "status_address=::" in your burp-server.conf. That will make it listen on IPv4 and IPv6 on all addresses, if that is really what you want.


If you leave the default status_address and want to run the status client locally on the server, there is no problem as the server supports "::1".
If you want to run the status client remotely, you will need to set the address in burp-server.conf anyway.

The default client burp.conf has 127.0.0.1 as the default server address, so that may be what has caused you confusion. I will update the default client burp.conf so that it mentions setting it to "::1" if you need to.

**Comment by grke** [comment]
Actually, I have now made the default client burp.conf have either 127.0.0.1 or ::1 depending on whether /proc/net/if_inet6 exists.
