### ISSUE TITLE
burp -a s very slow

### ISSUE THREAD

**Issue by nfp007** [grke/burp#322]
It takes several minutes to open monitor. There is around 100 server configured for backup.

**Comment by grke** [comment]
I believe that burp-ui is currently more stable than the
burp-2 built-in ncurses status monitor, so you will probably be better off
using burp-ui for now. And it looks prettier.

Although, it may be the case that it is the server-side part of the monitor
that is slow. If you have more and more clients simultaneously accessing your
disk, they will start to become slower, and the monitor will start to become
slower because it also has to access your disk to get various bits of
information.

**Comment by nfp007** [comment]
All other processes were stopped. So it is not the case.
I'll try the burp-ui

**Comment by grke** [comment]
Something is definitely slowing your disk access down though, otherwise you wouldn't be having problems with burp deleting old backups.

**Comment by laapsaap** [comment]
What file system are you using? I am getting very poor performance lately so been experimenting with different file systems.

**Comment by nfp007** [comment]
Hi,

i'm using zfs now. But it was slow also on xfs, i dont think it is FS
related.

regards

Radovan

**Comment by laapsaap** [comment]
I am not sure why people expect XFS to be fast, XFS is horrible with many small files. My experience with XFS and burp wasnt nice, its much better now on EXT4.

**Comment by nfp007** [comment]
we had bacula before so xfs was nice for that. and it was not possible
to change the fs in the process. but we switched to zfs which is much
better, but still it is not enough for listing 100 servers :-)
how many server do you have?

**Comment by grke** [comment]
I acknowledge that there are problems with burp-2 status monitor.
There are still a few items in the TODO file in the source code for it.
However, I believe that the on your system is not the monitor's fault, it is your choice of file system.
I am closing this issue, and leaving the other 'burp -a s' one that you created open.

**Comment by grke** [comment]
https://github.com/grke/burp/issues/326
