### ISSUE TITLE
How to open backup files directly from server?

### ISSUE THREAD

**Issue by arbrkic** [grke/burp#329]
Hello,

I have CENTOS 7 as BURP server with couple of Windows machines which are backed up on daily basis.
When I restore backup files directly to a client machines it works with no problems.

When I log in to server directly with SFTP and try to open files as a root from server it is not possible because files looks like they are messy and unreadable. 
This is example of one simple notepad document with 1 word inside opened directly on server:

http://s27.postimg.org/trstm4g0z/image.jpg

Also,
file with all logs is attached so I would be grateful if someone could take a look and try to open this ?

http://www.filedropper.com/adnan

Thank You

**Comment by grke** [comment]
Hello,

This is not the burp-users mailing list.
The mailing list is here:
https://lists.sourceforge.net/lists/listinfo/burp-users
Again, if you need more help after this reply, please join the mailing list.

There are three layers of things to deal with when trying to directly open Windows files backed up by burp:
1) Encryption. If the client encrypted the file, you cannot open it directly.
2) Compression. If you did not do the backup with compression=0 on the server side, you will need
to decompress the file. For example, using the linux command line: gunzip -c file.doc > ~/file-uncompressed.doc. If the file was not compressed, you can go direct to step 3.
3) VSS headers. By default, Windows files backed up with burp will contain Windows VSS headers 
and footers prepended and appended to the actual file data. If you want to open the file directly, you
first need to remove these. There are a few options:
a) Remove the VSS after you have backed up with the 'vss_strip' linux command line tool that comes with burp. For example: vss_strip -i file.doc -o ~/file-stripped.doc, or vss_strip -i file-uncompressed.doc -o ~/file-stripped.doc.
b) Do not back up the VSS headers/footers in the first place. Set 'strip_vss=1' in your burp configuration. The disadvantage of this is that you lose metadata that would be kept if you restored
via the burp client.
c) Tell burp to back up the VSS headers separately from the file data. Set 'split_vss=1' in your burp
configuration. The disadvantage of this is that backups are slower because it has to deal with
three file system entries for each single Windows file.

I would recommend setting compression=0 and using vss_strip to remove the VSS afterwards.

If this is too difficult, I would suggest that you look at installing burp-ui, as I believe it has a feature
that runs vss_strip for you.
