### ISSUE TITLE
Reference to Puppet module in BURP docs

### ISSUE THREAD

**Issue by tobru** [grke/burp#344]
We created a Puppet module to install and configure BURP and published it at https://forge.puppetlabs.com/vshn/burp. If you want you can put a reference to it somewhere in the BURP documentation.

**Comment by grke** [comment]
Hello,

Thank you for that, I really appreciate it.

Puppet is not something that I use, so I haven't tried the module out, and I don't really have time to do so.
So, I am not going to mention it in any burp documentation for now as I am not comfortable recommending things that I haven't personally had experience of. The same applies for things like nagios plugins that people have written too.
Possibly, at some point I will try to use it to help set up my automated test machines rather than my
own funky scripts that I currently use.

Once again, thank you.

**Comment by tobru** [comment]
No worries! Feel free to do it as you like =) We're currently rolling out BURP as our main backup tool, replacing BareOS. So we will have some more experience with the Puppet module and BURP usage in the next few months... Thank you for this great backup tool! We tested many tools and yours was really the greatest.

**Comment by grke** [comment]
That's great! I hope it continues to work out for you.
