### ISSUE TITLE
[will not descend: file system change not allowed] message should not be warning, but info

### ISSUE THREAD

**Issue by AdUser** [grke/burp#426]
Subj. It's expected behaviour when ``cross_all_filesystems=0``.

Also this triggers annoying email message when `notify_success_warnings_only = 1` is set, even if backup is successfull.

This is for version 1.3.48, but looks like this also exists in code.

**Comment by grke** [comment]
OK, that sounds reasonable.

**Comment by grke** [comment]
Sorry, I came to look at this again today, and I realised that this is actually not a reasonable thing.

If you want to not back up across some mount points, you need to specifically exclude them with an 'exclude=' line (or similar), then the warnings will stop.

Otherwise, I risk people not realising that they are not backing up some of their stuff.
'cross_all_filesystems=0' is the default.

Closing.
