### ISSUE TITLE
Locale and encodings mess up protocol 1 backups (strcmp)

### ISSUE THREAD

**Issue by sberthelot** [grke/burp#429]
I spent some time debugging a strange problem we have had on our test platforms for burp2.

To prepare for seamless migration we tried to upgrade some of our burp1 clients with burp2, keeping procotol = 1.
Some of them were backing up large amount of data that seemed not related to changed files.

It took some time to find what was causing this behavior since the problem is somewhat complicated to solve especially when trying to not start backing up everything again ( = keeping history)

Here is what I found, I hope you will be able to understand my explanation, comments are welcome :smile:

(everything related to protocol 1 only, I did not try to figure if protocol 2 is affected)

- in phase 1 client sends the complete list of files and attributes to the server
- in phase 2 the server didn't find some files in manifest (some details later) and asks for files that actually didn't change, backing them up again
- in phase 3, when server merges manifests I found that files were not sorted anymore, especially those files backed up again

From what I understand, in phase 1 client sends files (using find.c functions) using strcmp to order them (fsops.c my_alphasort() ). But I assume on our systems strcmp is more or less locale aware thus doesn't order files with special chars the exact same way that they are to be found in the manifest.
The code seems (on purpose) to assume the manifest is always correctly sorted then when it isn't it stops looking for files as soon as the order is broken or the end of manifest found (that's why files out of order are backed up again) (note: maybe add an option to check that manifest is correctly sorted for a particular backup or add this in verify operation ?)
But when merging manifests another sort function (pathcmp) is used and it doesn't rely on locale at all and at least doesn't produce same results as strcmp.

I'm pretty sure the same function should be used for both, especially a locale independent one (I would assume the best candidate is pathcmp)

To reproduce this problem you can do the following :
- setup burp2 in both server and client (with protocol = 1)
- use an UTF-8 aware locale (my glibc is 2.17 btw)
- add files with both special characters and metadata (ie: xattr) to the included files
- do at least 2 backups in a row

In my test environment I always get files with special characters and metadata backed up as being both new and deleted at the same time (looking at the statistics). Looking at the manifest I see the metadata only of those files at the very beginning and file entry with same name at bottom (ie: using "éé" for filename, LANG=fr_FR.UTF-8, it may change according to special chars used if you test)

Using a C locale (LANG=POSIX) when starting both server and client makes everything work correctly, as long as the manifest was correctly sorted before.

I'm going to try a manifest re-order or cleanup so that we'll have to backup at most files with special chars for some test clients on slow links ; I'm wondering whether a manifest sort order fixing tool may be less time consuming to code.

I don't know at all if protocol 2 is concerned but being locale independent seems mandatory to me, I wonder how other OSes (not tested) behave according to this matter (client file sorting and server manifest merging sorts should always return same result which seem to be an "interesting" problem to solve across different systems)

Sorry for this long post and I hope it can be fixed without much hassle :smiley:

**Comment by grke** [comment]
Hello,

Thanks for investigating this problem and writing it up.
Protocol 2 uses the exact same find and manifest sorting code as protocol 1.

I think that strcmp() is locale independent.
I think that strcoll() is the locale dependent equivalent.
I never use strcoll() anywhere.

Therefore, I think that this problem is most likely to be something to do with the pathcmp() function
I wrote myself.

Having now checked a few implementations of strcmp(), it looks like they are comparing unsigned chars. And pathcmp() is using signed chars. This seems like it might be something to do with it and could well cause problems with characters with high numbers.
But I don't get why the locale would make any difference. I don't follow from your explanation whether it did or not. Maybe it is broken in the same way if you start with a C locale and no backups.

I should definitely be using the same thing in both places.
That should be pathcmp(), I think, like you said. Switching to it in both places rules out any crazy locale-dependent strcmp() implementations.

I don't have time to investigate much further right now, but what I will do soon is add more test cases to utest/test_pathcmp.c and try to prove/break/fix what pathcmp() does with high numbered characters.


I just checked burp-1.4.40, and it uses pathcmp() when sorting on the client side.
Recent burp-2 is using strcmp().
I think I refactored a bunch of similar-looking stuff and then chose the wrong sort function.

I would imagine that things would work the same as burp-1 if you went to src/fsops.c and changed
my_alphasort() and rev_alphasort() to use pathcmp().

If this is the case, should I just do that change, or should I also fix pathcmp() to use unsigned chars?
Doing both means that if you upgrade from burp-1 to burp-2 you still have the problem on the first backup after the switch.
I guess I need to do a manifest fixing tool. All it probably needs to do is split out entries that have characters higher than the sign boundary, then sort those. Then merge them back together.

**Comment by sberthelot** [comment]
Thanks a lot for your answer, it makes things much more clear !

I have just done additional testing and actually the locale has nothing to do with this issue, only char signedness, you were totally right on this.

But moreover, when replacing the sort function in my_alphasort by pathcmp (instead of strcmp) it also seems to fix (after the next backup) the manifest since wrongly ordered files are backed up again and then added at the "right" place.

Personally I would expect that using burp-2 with protocol 1 to behave the same as burp-1 so I would suggest to use pathcmp in my_alphasort (and revsort) to keep compatibility and fix this issue at the same time.
As for protocol 2, the question is, does changing the sort order improve anything ? From what I understand the manifest has to have a consistent and stable ordering (and always the same both on client and server in any phase) ; if the sort function is not completely what we would expect (unsigned chars) but fulfill this requirement and does not introduce incompatibility between OSes, it seems OK to me, maybe more stable than system calls that may change across systems or versions.

I've prepared an almost-trivial patch to fsops.c and waiting your answer to see if it's suitable to make a pull request for this.

Thanks again for your work and explanations !

**Comment by grke** [comment]
Hello,

Don't worry about making a pull request.
I know what the fix is, and I will be adding additional tests.
I would prefer that pathcmp() use unsigned chars, as it means I would be less likely to break burp in a similar way again.
But that's really annoying for everybody else.
So maybe I will leave pathcmp() as it is for now and fix it in some future version if it really is a problem.

**Comment by grke** [comment]
Fix now in git master, with tests.
