### ISSUE TITLE
Allow restore during a backup

### ISSUE THREAD

**Issue by kronos-pbrideau** [grke/burp#450]
Here is what we discussed previously in the mailing list, to keep track:
https://sourceforge.net/p/burp/mailman/message/35219023/

Currently, in the case a backup is long to process (let's say 23 hours), you can only restore backup of this node manually (which is a pain) or restore during the 'off' hour

It would be nice to be able to restore a backup while a backup is taking place.

**Comment by grke** [comment]
Thanks for creating the issue, as I forgot soon after the discussion.

**Comment by grke** [comment]
I think that this requires that the server child process places lockfiles in storage directories of individual backups, rather than at the client level.

So, when the client asks to list backup 5, the server child locks backup 5, then lists it.
So, while backup 5 has a lock in it, you cannot do any other operation on that backup.
A backup action would lock the backup that it is working on, and possibly the most recently completed one.

The status monitor stuff would have to change to indicate the status of individual backups, instead of the client. Perhaps the overall client status would be an aggregation of the backup statuses.

The server child processes would need to pass additional information on backup number back up to the parent, and the parent would need to write that back down to status server child processes.

**Comment by grke** [comment]
Now working on this.

**Comment by grke** [comment]
This is now merged into master.

If you want to restore whilst backups are finalising, I would recommend that you have the
hardlinked_archive=1 option set. Otherwise you will get errors when you try to restore a file/delta that
has been jiggled around in the 'current' directory. The hardlinked_archive=1 option means that the restore doesn't need to leave the backup number that you are interested in in order to find files and
deltas.

I have not yet changed the json status monitor output, as I need to check that Ziirish will be happy with them in burp-ui.
I have created issue #568 for the monitor stuff.
It is actually not a new issue, as listing was previously possible at the same time as other operations.
