### ISSUE TITLE
Compile and run utests for Windows

### ISSUE THREAD

**Issue by grke** [grke/burp#477]
Currently, the tests in the utest directory only work for linux/mac machines (although there are various end-to-end tests that do run on Windows).
For this, a binary called 'runner' is built and executed.
It would be very useful to run 'runner' under Windows.

Prerequisite:
Add the 'check' library to burp-depkgs.

The 'runner' binary needs to built, copied to the Windows test machine, and executed.

Decide whether to include it in the Windows installer, or to copy it across separately.

**Comment by ziirish** [comment]
Hello,

I don't think the 'runner' should be part of the Windows installer since it's mostly a developer tool.
I suppose it would be nice to ask a user to run the test suite against its environment, but it should not be the case for the vast majority.

An alternative would be to distribute it as part of a burp-dev.exe package or something.

/my 2 cents

**Comment by grke** [comment]
This is now done, but it is currently part of the windows installer, not separate.
If this ends up being a problem, I will change it, but for now, that is how it is.
