### ISSUE TITLE
Could not find ssl_cert : No such file or directory

### ISSUE THREAD

**Issue by Spheerys** [grke/burp#481]
Hi,

I'm using Burp 2.0.47 on a server, and I have 5 working Burp clients
But on one client, Burp dosen't want to connect to the server !

When I'm launching `burp -a b` I have theses errors : 
```
2016-09-21 11:59:27: burp[15296] Could not find ssl_cert /etc/burp/ssl_cert-client.pem: No such file or directory
2016-09-21 11:59:27: burp[15296] Could not find ssl_key /etc/burp/ssl_cert-client.key: No such file or directory
2016-09-21 11:59:27: burp[15296] Could not find ssl_cert_ca /etc/burp/ssl_cert_ca.pem: No such file or directory
```
And effectively, a `ls -al /etc/burp/` give me : 
```
total 40
drwxr-xr-x   5 root root 4096 sept. 18 20:29 .
drwxr-xr-x 102 root root 4096 sept. 18 20:29 ..
drwxr-xr-x   3 root root 4096 sept. 18 20:29 autoupgrade
-rw-r--r--   1 root root 4497 sept. 18 21:21 burp.conf
-rw-r--r--   1 root root 6406 sept. 18 20:29 burp-server.conf
drwxr-xr-x   2 root root 4096 sept. 18 20:29 CA-client
-rw-r--r--   1 root root  781 sept. 18 20:29 CA.cnf
drwxr-xr-x   3 root root 4096 sept. 18 20:29 clientconfdir
```

On other clients, I have the ssl certs in this place !

I have uninstalled Burp on this problematic client, delete all conf files, recompile it, checked three times the `/etc/burp/burp.conf` file without find any clue.
Same for the `/etc/burp/clientconfdir/problematicserver.conf` on the server side !
Everything look good (I can post them is need)

What did I miss ?

**Comment by grke** [comment]
Hello,

Does 'burp -a b' show anything other than the three lines that you posted?

Does the server side log anything?

To help on the server side, I recommend temporarily setting 'stdout = 1' in burp-server.conf, and
running the server with 'burp -c /etc/burp/burp-server.conf -F', then running 'burp -a b' on the client.

**Comment by Spheerys** [comment]
After 2/3 minutes, I have this error in addition of the three lines : 
```
2016-09-21 12:20:41: burp[28695] could not connect to burpserver.domain.net:4971

```
On the log, I have nothing from this problematic server, but I have things when another working client is running.

I will try your last recommendation and I'll be back :)

**Comment by Spheerys** [comment]
I tried what you said and I had  nothing more about the problematic client

**Comment by grke** [comment]
```
2016-09-21 12:20:41: burp[28695] could not connect to burpserver.domain.net:4971
```

This means that the network connection is not being made to the server.
The server therefore never hears anything from the client and logs nothing.
And the client never manages to do the certificate exchanged, because it never connects to the server.

Have you got the address correct in the client burp.conf?
If you have put a name that needs to be resolved into the client burp.conf, can the client OS resolve that name?
What happens if you try to ping burpserver.domain.net from the client?

Have you got the port number correct in the client burp.conf?
What happens if you try to telnet to port 4971 of burpserver.domain.net from the client? 

Is there a firewall between your client and the server?
Is it blocking the burp server's port?

Is the server using ipv4 or ipv6?
What about the client?

**Comment by Spheerys** [comment]
OK solved !
It was a firewall rule's issue !
Thanks for your help :)
