### ISSUE TITLE
Scheduler does not seem to work properly

### ISSUE THREAD

**Issue by chlarsen** [grke/burp#485]
Dear All,
First of all, thanks a lot for this terrific piece of software. Easy to set up, highly efficient, fast and secure. Great stuff.
I am running burp v. 1.4 .40 on FreeBSD 10.3, compiled and installed from ports.
Everything works well, save for the fact that I get a lot of incremental backups done.
I have left the timer_arg settings at their defaults:
````
timer_arg = 20h
timer_arg = Mon,Tue,Wed,Thu,Fri,00,01,02,03,04,05,19,20,21,22,23
timer_arg = Sat,Sun,00,01,02,03,04,05,06,07,08,17,18,19,20,21,22,23
```` 
On the clients ,the crontab has this entry:
````
# burp: ask the server, whether it is time for a backup
01,31   * * * * root    nice -n 20 burp -a t >> /var/log/burp-client.log 2>&1
````
What happens is that the first timer_arg = 20h seems to get ignored. Hence, i end up with hourly incremental backups during the scheduled time slots, where backups are permitted (but should only occur every 20 hours).
Am I missing something stupid?
Thanks a lot for your help!
Chris

**Comment by grke** [comment]
Hello,

This is probably something to do with the 'date' command on FreeBSD not being the same as the 'date' command on most linux machines, or the locale causing the 'date' command to do something unexpected.

You can take a look at debugging the timer script (normally in /usr/share/burp/scripts/timer_script), which uses 'date' to match the timer_arg parameters that you gave it.

There is a task in the github issue list to look at internalising the timer_script, so that discrepencies
between OSes like the 'date' command, or locale differences, no longer matter.
I haven't got around to doing it yet though. 
It is issue #209.
If you want to continue to comment, comment on #209.
I will close this one.

Thanks!

**Comment by grke** [comment]
By the way, other FreeBSD users already commented on #209 and say they got the timer script to work with 'gdate'.

**Comment by chlarsen** [comment]
Thanks a lot for the heads-up. This is very helpful.
Have a great weekend,

Chris
