### ISSUE TITLE
Burp verify fails

### ISSUE THREAD

**Issue by githubcdr** [grke/burp#490]
Hello,

I noticed that burp verify (burp -av) doesn't seem to detect changed files after creating a backup. (protocol2 burp 2.0.48)

Steps to reproduce;

1. Create a backup of /etc
2. Validate this backup without altering any file, no problems.
3. Edit /etc/hosts and verifiy again
4. Burp returns with no warning or error

Burp does not seem to notice the change in checksum for /etc/hosts and returns no warning. I would expect an checksum warning for the file /etc/hosts.

Is this a bug or intentional?

**Comment by grke** [comment]
Hello,

The purpose of the feature is to verify files inside backups against their checksums inside backups.
It does not compare files outside of the backup against checksums inside backups.

It sounds like maybe the feature that you want is something similar to my plans for the 'estimate' or 'diff'
features, where burp would tell you what files have changed on the client (new/changed/deleted), without actually doing the work of backing them up.

**Comment by githubcdr** [comment]
Hi,

That makes sense. If I understand correctly there is currently no way of validating a backup with the files on the system? This would be a nice feature to have.

Maybe "verify" should be renamed to "integrity"?

**Comment by grke** [comment]
Yes, there is currently no such feature.

Hello,

No, I will not rename "verify" to "integrity".
The word "verify" makes sense to me and the feature has been named that since the beginning of burp with no problems.

The 'diff' functionality will provide you with the feature that you want one day, when I get around to it. This is described in this thread, linked from issue #75
https://sourceforge.net/p/burp/mailman/message/31662688/
