### ISSUE TITLE
Disaster recovery when client certificates have been lost

### ISSUE THREAD

**Issue by kellogs** [grke/burp#496]
First of all, I would like to thank you for such a nice piece of software which answers real needs. 

I have been working around for some years with duplicity, gpg, rysync backup and helper tools. And it was a long time I wanted to use a software like burp. It convinced me in 30 minutes. Thanks!

One question arises. What happens in case of disaster recovery? Is there a way to retrieve client certificates using command lines when the client has been destroyed (lost, stolen, faulty) without access to the server. I have been looking for client certificates stored on the server side, but did not find them. Are there reasons why not storing them on the server side ? Or did I miss something?

Kind regards,
Kellogs

**Comment by grke** [comment]
Hello,

Thank you for your kind words.

The server has the client certificates in /etc/burp/CA/, because it signs them during
the exchange, but it doesn't keep the client key.

No, you cannot retrieve any files without first authenticating. That would be
very insecure, because anybody would be able to get your files.

If you don't have access to the server, you will need to save your certificates
somewhere else in order to be able to connect again.

If you do have access to the server, you can easily remove the old certificates
on the server side and re-exchange certificates as if your replacement client
is new (which it is, really).
