### ISSUE TITLE
Protocol 2: removing finished backup doesn't free occupied space

### ISSUE THREAD

**Issue by marcin-github** [grke/burp#503]
burp-2.0.48, protocol 2.
When I make a backup, next I do `burp -a delete -b 1` size of burp directory doesn't go down. When I execute backup once again burp doesn't dedupe data, size of backup grows up. With empty burp backup directory:
`for x in {1..10}; do burp -ab && burp -a delete -b 1 && du -hs /var/spool/burp; done` 
gives:
822M    /var/spool/burp
1,7G    /var/spool/burp
1,7G    /var/spool/burp
1,7G    /var/spool/burp
1,7G    /var/spool/burp
1,6G    /var/spool/burp
1,7G    /var/spool/burp
1,7G    /var/spool/burp
1,7G    /var/spool/burp
1,7G    /var/spool/burp

so after second backup size of spool directory doesn't grow up.

**Comment by grke** [comment]
Hello,
This is because the shared data files don't get deleted until the champ chooser process for the dedup_group runs.
Having said that, the deletion process needs to regenerate the client dindex files first, and it is not
doing that yet. I am working on a patch for that
Issue #494 is related, which is that data files are deleted prematurely and you lose your data.

**Comment by grke** [comment]
Sorry, I am discontinuing work on the protocol 2, which has never been production ready, and it is removed in the latest release of burp.
