### ISSUE TITLE
burp don't follow symlink

### ISSUE THREAD

**Issue by leonel918** [grke/burp#505]
Hi, is it possible to follow symlinks to directories for backup? I need to backup the contents of a directory  pointed by a symlink, e.g. in the configuration file i have: "include = /principal/dir", and into /principal/dir there is symlink to /secondary/dir (/principal/dir/link -> /secondary/dir), but when burp performs the backup it doesn't copy  /secondary/dir. I tested enabling "cross_filesystem" option setting "cross_filesystem = /principal/dir" but there is no change in behavior.
I hope you understand me.

Regards.

**Comment by grke** [comment]
Hello,

I understand you fine. :)

Sorry but no, there is no way to make burp follow symlinks as if they were directories.
You would have to list each /secondary/dir as an include line, or start from a directory that contains them both (like '/').
I don't want to add this as a feature either, because it would make the code much more complicated.
