### ISSUE TITLE
Burp with NFS share folder.

### ISSUE THREAD

**Issue by nhanvolac** [grke/burp#576]
Hello,

After using the storage local at: 
`directory = /var/spool/burp`
I've changed the storage of Burp to QNAP server (via NFS port):
- I rename the burp folder at (/var/spool/burp) to burp1 folder.
- And reate a new burp folder. 
- mount nfs folder on QNAP server to /var/spool/burp via command.
`mount -t nfs IP:/foldershare /var/spool/burp`
When check gain with client, it is fail with SSL.
I try a new one, and run `burp -a m` -> it ok.

![image](https://cloud.githubusercontent.com/assets/20902182/26737948/81ff7988-47f6-11e7-9436-744f1426fe4d.png)

But when try the command:` burp -a t` -> It hang and closed after 7200 (time out) (I don't remember exactly the out put), It fail both Windows OS and Linux OS.

![image](https://cloud.githubusercontent.com/assets/20902182/26738157/3ac3a1ce-47f7-11e7-84c2-f056bc70b59d.png)

But when checking on QNAP folder share, I only see a file with name "lockfile" with the folder corresponding to the name of the client.

We need configure more for this case? 

Thanks.

**Comment by grke** [comment]
Hello,

Sorry, I have no idea.
I just pointed my own burp server at an NFS-mounted directory, and 'burp -a m' and 'burp -a b' for the first time, and it worked fine.

Did you restart the burp server?
Does it work when you don't use NFS?

**Comment by grke** [comment]
The only change I made in my test was to change the 'directory' option in burp-server.conf, and restart the burp server.

**Comment by nhanvolac** [comment]
Hi,

Thanks for your response.
`Does it work when you don't use NFS?` --> It work fine when I storage at local storage. 
`Did you restart the burp server?` I've restated the burp server but it cannot backup.
So I will check again, It maybe due to we need more port instead of only NFS port.

Thanks again,

**Comment by pablodav** [comment]
I had some experience with NFS using NAS, there is some issues in performance due that burp requires many small 4k files when using librsync and hardlinked_archive=0 also makes more disk IO usage. 

It worked but finally I have moved to use same NAS but with iscsi. 

Today my burp servers has NAS with iscsi and works pretty well. 

Another trick I recommend for better performance using `librsync` and `hardlinker_archive=0` is to use `manual_delete=/path/to/trash/` (where it should be on same FS as the NAS storage). 
Then you setup cron task to delete `/path/to/trash` once a day, it will enhace phase4 because will not delete old backups during this phase, instead it will move the dir to `/path/to/trash`. 

I'm use this setup on production on 5 servers today and works pretty well, I use my roles: https://github.com/grke/burp/wiki/Automated-deploy-and-maintenance 

With https://github.com/CoffeeITWorks/ansible_burp2_server is easy to keep these settings same on all servers, or change one only changing vars per servers. 

The setup for burp_config and cron task for manual_delete is automatic only with this var: 

```yaml

# Configure Burp manual delete
burp_manual_delete_enabled: true
```

Kind regards,
Pablo.

**Comment by nhanvolac** [comment]
Thank you so much for your information, Pablo.
I think I'll take it as my experience  💯 👍 
Have a nice day, Pablo ^_^

**Comment by pablodav** [comment]
Glad to help, 
Have a nice day you too!
