### ISSUE TITLE
burp protocol 2 vss_split = 1 nor vss_strip = 1 option isn't honored

### ISSUE THREAD

**Issue by deajan** [grke/burp#617]
Just a quick note to tell you that vss_split = 1 works with protocol 1 but doesn't seem to work with protocol 2.
Used the same client, backing up to the same server running two instances (p1 and p2), with the same config files.
Restoring data from protocol 1 gives direct files, and from protocol 2 I have to use vss_strip.

Is that intentional ? If yes, maybe you could add a quick note to the docs :)

Best regards.

**Comment by grke** [comment]
Hello,

 The 'vss_split' option means to store the vss parts separately to the main file data as separate nodes in the file system.
Protocol 2 does not store files as nodes in the file system, so 'vss_split' makes no sense, whereas
'vss_strip' does.

Yes, adding a note in the man page would make this clearer.

**Comment by deajan** [comment]
Indeed, makes sense :)
Just to be perfectly clear, what do the VSS headers and footers contain ?

**Comment by deajan** [comment]
I actually changed split_vss = 1 to strip_vss = 1 on a protocol2 backup, and I still get restored files with vss headers.

I really think the protocol 2 restores should be able to strip the vss metadata when restoring to linux, since burp-ui also would use those restored files to compress them as archive and send them to the user, who wouldn't be able to use the files with vss metadata.

**Comment by ziirish** [comment]
Hello,

Just a quick note to say that burp-ui is already able to deal with vss_header ([here](https://git.ziirish.me/ziirish/burp-ui/blob/254f683a58baef2a7943af0895d7b1f65e79fc4c/burpui/misc/backend/burp1.py#L920) is the piece of code if you are interested).
But right now, protocol 2 is not supported (a couple of things are probably already working, but I haven't tested anything about protocol 2 yet).

**Comment by grke** [comment]
OK, I was mistaken - both split_vss and strip_vss are unsupported in protocol2.
I don't think it is worth implementing them in protocol2 though, since the original point of them was to help people just copy the files directly back out of the storage directory, and you can't do that at all in protocol2.
I think what you want/need is to be able to skip them in restore.

**Comment by grke** [comment]
Answers to other questions:

"Just to be perfectly clear, what do the VSS headers and footers contain ?
NTFS permissions and EFS info ?"

"Maybe having protocol 2 strip the vss info when restoring to linux would be a good idea ?"
Yes, it is.

"Would vss_strip = 1 speed up backups (a lot) ?"
I don't think it would make any significant difference in either protocol.
I think vss_split would be significantly slower in protocol1 because the server has to open and close at least twice as many file descriptors to store the data separately, and also deal with twice as many inodes.

**Comment by deajan** [comment]
@grke Indeed, since there would be no speed improvements by skipping / splitting vss on backups in protocol2, strip vss metadata in linux restore would be perfect.

**Comment by deajan** [comment]
Got to install and test burp 2.1.22 today.
Most restore operations work like a charm, without any further warning messages.

As of today, when I restore a protocol 2 backup from a windows client on a linux box, I have to vss_strip all files in order to be able to use them properly.

Got a basic script for doing so, since vss_strip can't perform this inline, I have to make copies first which makes huge IOs.
```
#!/usr/bin/env bash

if ! type vss_strip > /dev/null 2>&1; then
        echo "Could not find vss_strip."
        exit 1
fi

if [ "$1" == "" ]; then
        echo "Usage:"
        echo "$0 /path/to/apply"
        exit 128
fi


find "$1" -type f -print0 | while IFS= read -r -d $'\0' file; do
        echo "Unstripping file [$file]."
        mv -f "$file" "$file.old"
        if [ $? != 0 ]; then
                echo "Could not move $file to $file.old"
                continue
        fi
        vss_strip -i "$file.old" -o "$file"
        if [ $? != 0 ]; then
                echo "Could not vss_strip $file.old to $file"
                continue
        fi
        rm -f "$file.old"
        if [ $? != 0 ]; then
                echo "Could not delete $file.old"
                continue
        fi
done
```

I'd be really happy of some next version could strip vss data on linux restores for protocol 2 :)

**Comment by grke** [comment]
In master, the client can now strip the vss data on linux restores for both protocols. You need to give the client the '-x' option to enable this behaviour.
