### ISSUE TITLE
Defragmenting a protocol=2 dedup_group ?

### ISSUE THREAD

**Issue by sberthelot** [grke/burp#660]
Hello and I think I'm reporting again something that may be hard to "fix" or adjust, thanks for your patience :smile: 

We have now more than 1 year of backup with decreasing retention on some of our test servers and we see high disk usage.

I was wondering when the data files are deleted and came to think about some sort of fragmentation.
From what I understand those files hold many block of data from different original files (to avoid the high inode usage on protocol 1) but then they may only be deleted when all original files have vanished or at least all content is not used by any backup (from any client in the dedup_group).
Is my understanding OK ?

Then a small permanent file may occupy a full block with other obsolete data that have been removed until either :
- the block is fully rewritten "in place" with only "currently active" data (then how about data offsets or pointers in this block ? they'll have to be changed everywhere...)
- the block is duplicated to a new block with also only "currently active" data and then the old one can be dereferenced and removed (again new references have to be synced on all clients using the old block)

With that said it looks a lot like a defragmentation algorithm and would certainly have a somewhat heavy usage on disk.

Did I miss something ?
It's the only explanation I found for high disk usage currently on pools with protocol 2 (ie: for a dedup_group with only 1 client if I sum up all transferred data from logs I get 65GB and the "data" dir on disk goes for 114GB now ; a df on the client shows about 95GB and has small new or modified data everyday : less than 500MB)

Thanks for you help and you explanation, I'm looking forward to reduce our disk usage for backups if possible.

**Comment by grke** [comment]
Hello,
I think that your understanding is accurate.
I currently have no way of 'defragmenting' the dedup_group directories.
You are right, to do such a thing would take a lot of disk usage, and it would require lots of very careful locking. It is probably a large amount of work to implement.

The data files have the format of a length, and then a block of data, like this:
[B10BE][data][B094D][data][B12D8][data]...and so on...
Other files (the manifests and sparse index, for example), reference the offset into the data file.

If we could be sure that certain offsets are no longer referenced, a data file could be rewritten like so:
[B0000][B0000][B12D8][data][B0000]... and so on...

I'm sure I could make that happen with a large amount of effort, but it wouldn't be fast.
A plus to this idea is that only one data file would be rewritten at a time.

It would be even harder/slower to combine chunks into new manifest files, because the offsets would
need to be rewritten in other files, all at the same time.

**Comment by sberthelot** [comment]
Hello,
My wording was not really accurate but I think I got the idea right, thanks for your answer and the explanation.

I understand why we have a disk usage higher than what I thought first. We had the same kind of "situation" with dovecot and the mdbox (multi-dbox) format. It packs messages to the same file but then the author added an offline utility (used in a cronjob on low activity) that repacks new data files with only active messages and drops the old one ; to my knowledge this would need and indirect map index. More info here : https://wiki2.dovecot.org/MailboxFormat/dbox (especially on "Expunging ..." paragraph :smile:  )

I understand this is a complex feature to add, maybe zeroing blocks would be efficient enough at first ; if the blocks are 0-indexed (is offset used in sparse and manifest files a byte offset or a chunk number ?)
Making the file sparse (on modern file systems like ext4, xfs, ... , thus keeping the byte offset untouched) could also be a "solution".

Sorry to report this somewhat late in development (and maybe design if you need to change some part of it) of protocol 2 in burp but I personally think it is an important matter for "production"-readiness state.

**Comment by grke** [comment]
Sorry, I am discontinuing work on the protocol 2, which has never been production ready, and it is removed in the latest release of burp.
