### ISSUE TITLE
Request of Continuous Data Protection (CDP) feature

### ISSUE THREAD

**Issue by samuelxhu** [grke/burp#684]
Hi, 

I have a use case of CDP, i.e. whenever a file or directory changes within my backup domain, i would like the client would immediately trigger a sync (backup) procedure, and send the data to the backup server. Since Burp is based on librsync and working in PUSH mode, I think BURP would be the best candidate to do it. How hard to add this feature in Burp? 

In Linux this is quite straitforword, e.g. one can continously synchronizing using e.g. watch.sh (https://github.com/drunomics/syncd/blob/master/watch.sh) or lsyncd (https://code.google.com/archive/p/lsyncd/) (these programs use inotify to constantly monitor the source directory and immediately copy over any changes). But in Windows, i am not familiar...

I have some budget and would like to sponsor such coding activity. If anyone is confident and interested to do so, pls contact me at samuel.xhu@horebdata.cn

thanks and regards,

Samuel

**Comment by grke** [comment]
(I also sent this in reply to a direct email)

Hello,

Is this what you want?

1) You give burp a list of directories or files.
2) Something in the list changes on the client.
3) This triggers burp to do a backup as usual, according to its current
   include/exclude rules.

In this case, the burp client would still do a full scan of the
includes/excludes and create a new backup on the server.

As you say, on Linux clients it is probably easy and on Windows, I have
no idea without going away and starting to look at it. But maybe you
can easily do it with existing programs. All you need is some Windows
tool that runs a script on changes that calls 'burp -a b'.

Maybe this page can help you:
https://superuser.com/questions/226828/how-to-monitor-a-folder-and-trigger-a-command-line-action-when-a-file-is-created

**Comment by samuelxhu** [comment]
@deajan thanks a lot for the inotify information. I will take a serious look at it. 

5min/15min cycle is a near CDP option, though i really want to have a authentic CDP. why do you think burp backup on any file activity would be horrible? Isn't it working on rsync which only transfers data changes? 

By more complex code for instant updates BURP, what do you exactly mean? Perhaps an outline would be insightful enough :)

**Comment by deajan** [comment]
When burp is launched, it first compares all files on the client with the signatures of the files on the server, this takes generally some seconds to minutes, depending on the number of files you have.
Once the backup is done, there's a process running on the burp server which relocates files between the different backups of a client, creating multiple copies with the least disk space used.
So you'd need at minimum to wait some seconds / minutes between every burp launch.
If the client modifies files on a very regular basis (let's say every second), burp would be run continuously in a cyclic way, which IMHO is horrible, since once burp client has finished, server side hasn't finished relocating the files, but client is already launched again.

Continuous burp would mean to keep a ssl tunnel open, and send the files as they come.
Thing is that you won't be able to read all files (especially because you can't have VSS in this case), some files like databases won't be consistent, and there would be some kind of retention strategy code that must be done on the server side in order to keep multiple copies.

Just my 2 cents, @grke will probably have a way better insider view than I may have.

Professional CDP is always VSS aware (snapshots to have consistent data), so you'll have those 5min /15min since you simply cannot snapshot a disk every second.
User CDP (instant copy), when only non critical files are in use, could be achieved by having a one-way sync software with versionning.

What exactly are your needs ?

**Comment by samuelxhu** [comment]
@deajan thanks a lot for detailed explanation. It is interesting that you point out professional CDP does backup at the interval of 5-15 minutes. If this is the case, I suppose backupPC or Urbackup would be able to do it by scheduling the pulling operation more frequently.

I guess a truly CDP would rely on one-way sync function, perhaps combined with restoring functions. In terms of one-way sync, which tool do you think would be easier tailored towards backup software?

**Comment by deajan** [comment]
If I remember well, backuppc doesn't use an agent to connect (uses SMB/SSH ?), so it won't be able to pull VSS snapshots unless you install something on top of windows. Maybe they made progress since then.
Professional CDP can be achieved simply by burp, installing the client with a 5min timer and having the server set with a 15 min timer_arg delay, since burp uses VSS out of the box.
The CDP will depend on how much time it takes to update your copies. I suppose you should nevertheless disable retention in order for phase 3 & 4 to not happen.
Retention can be achieved by using zfs backend storage, which can be triggered before each burp CDP update.

There is no "true" CDP since instant copy won't handle open files.
I guess what you are searching for is simply a nextcloud/pydio setup.
Both products can handle versionning, and you may "restore" your files by going into the web interface and download whatever you need.

Generally speaking, most pros use 5/15min cycle CDP for backups, combined with a cluster file storage for instant replication (eg DFS-R or some fancier solution).

**Comment by grke** [comment]
Thanks, deajan, everything that you have written looks correct to me.

**Comment by grke** [comment]
Deajan's 5/15 minute cycle might work if you don't have a large number of files in your backup.
But you will end up with hundreds of backups, unless your retention is low.

**Comment by grke** [comment]
I think this is answered well. Closing.
