### ISSUE TITLE
Am I right that even the server-post-execution script doesn't fully await Phase 4?

### ISSUE THREAD

**Issue by rmast** [grke/burp#712]
I try to spawn a cascaded backup from the 'current' directory resulting from burp, but when I spawn it from the server-side post-execution-script the current directory still contains yesterday's backup. Phase 4 appears to end minutes later.

**Comment by rmast** [comment]
I'll let an inotifywait daemon log the changes to see what event I can use for an inotifywait workaround.

**Comment by grke** [comment]
Hello,

The server side post script runs after phase4, but before the server side child process has exited and relevant locks are removed.

**Comment by jirib** [comment]
Do I understand it correctly that server post script thus cannot be used to for example rsync just recently backup data as 'current' dir is not yet created for recent backup?

**Comment by grke** [comment]
Hello,

The 'current' symlink is already moved into place by the time the server post script runs.

If I remember rightly, the original purpose of me making the server post script was so that I could run an rsync job to copy the new 'current' somewhere else, whilst keeping the lock so that another backup wouldn't start at the same time.
