### ISSUE TITLE
Documentation on http site still indicating 2.0.x is unstable

### ISSUE THREAD

**Issue by TheNotary** [grke/burp#818]
Is it still true that we should only be using version 2 with extreme caution as noted at  https://burp.grke.org/protocol2.html ?  If so, it might be nice to update that html to indicate `2.3.x` or `2.x.x` is unstable so people understand that it's up to date.

**Comment by ziirish** [comment]
This piece of doc states that protocol 2 is still to use with caution. Burp supports both protocol 1 and 2 since version 2.0.The current stable version of burp is 2.2.18-------- Message original --------Objet : [grke/burp] Documentation on http site still indicating 2.0.x is unstable (#818)De : TheNotary À : grke/burp Cc : Subscribed Is it still true that we should only be using version 2 with extreme caution as noted at  https://burp.grke.org/protocol2.html ?  If so, it might be nice to update that html to indicate 2.3.x or 2.x.x is unstable so people understand that it's up to date.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/grke/burp/issues/818?email_source=notifications\u0026email_token=AADNZLYJXM5OBQOAQPPPD6LP7MWZZA5CNFSM4IDPRJ3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7CXEJA",
"url": "https://github.com/grke/burp/issues/818?email_source=notifications\u0026email_token=AADNZLYJXM5OBQOAQPPPD6LP7MWZZA5CNFSM4IDPRJ3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7CXEJA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TheNotary** [comment]
Ah, that makes sense, @ziirish thanks for the info!  I suppose it might be handy to clarify with a statement "As of release 1.n.n, protocol 2 is available for use, but use protocol 2 with extreme caution, it is not yet production ready." but now that you point this out, I shouldn't have assumed that the major releases coincided with which protocol was being used.  

Please close at your discretion and thanks again for all the hard work on this project!
