### ISSUE TITLE
Backups failing after redeploy of burp server

### ISSUE THREAD

**Issue by TheNotary** [grke/burp#821]
I've been building some infrastructure code to have a burp-server VM built.  It's meant to store all of it's backups state in `/mnt/freenas_file_system_backups` which is over NFS (certs are in a different location).  I just got backups working for my laptop, but after I destroy and rebuild the server, I see this error from the client:

> main socket 4: unexpected command in asfd_simple_loop(), called from maybe_check_timer(): e:003D:Finalising previous backup of client. Please try again later.

I only just now read the end part of the message, and sure enough, after waiting 5-10 mins (it's a 9GB backup), backups are now working again.  

I feel a bit silly creating an issue now, although I am curious what process the burp server is performing to get clients `Finalised from previous backup of client`.  Is is possible to invoke this process manually so that I can have that happen on the first boot of the burp-server in my infracode?

**Comment by grke** [comment]
Hello,

There are 4 phases to a backup, and they are explained here:
https://burp.grke.org/docs/shuffling.html

After phase 2, the client disconnects, but the server still has some work to do for phases 3 and 4 (the finalising steps).
Whilst the server is still busy in phases 3 and 4, you will get a message like the one that you saw. Phases 3 and 4 happen automatically after phase 2 without any interruption.

If the process is interrupted in some way (for example, by rebooting), then the state is detected and resumed again the next time the client tries to connect.

It is most probably possible to use a burp client process on the server-side in order to trigger this on boot if you really need it, using the -C 'clientname' option.

**Comment by TheNotary** [comment]
Ah, thanks for that info @grke.  That solution should do the trick I think.

**Comment by dimti** [comment]
@grke Hello.
I see something sitation, but finalising wont be finished.

My computer is freezes and disks on RAID+LVM some is broken. fsck correcting the disks. After that, finalising operation on burp wont be finished 10 days ago.

How i can stop this operation?
How i can see verbose status of this finalising backup?

I try to remove last backup, but not luck.

burp-server daemon not use CPU, lsof not showing used files in the backup. How to determine finalising is worked?

![image](https://user-images.githubusercontent.com/582144/83127134-78534e80-a0e2-11ea-9bf7-36ef8a55d9de.png)

![image](https://user-images.githubusercontent.com/582144/83127202-8acd8800-a0e2-11ea-8fe5-4e7477db527c.png)

![image](https://user-images.githubusercontent.com/582144/83127225-91f49600-a0e2-11ea-8f17-6ecbd83f42b6.png)

**Comment by grke** [comment]
Hello,

Once a backup is in the 'finalising' state, you cannot delete it, because the only way is forwards. The reason for this is that it may alter the immediately previous backup.
How did you try to remove the last backup?

Did you check any server-side logs?

**Comment by dimti** [comment]
Wow. Server side logs have additional info. Good.

```
2020-05-29 17:07:36 +0300: burp[150291] Begin phase4 (shuffle files)
2020-05-29 17:07:36 +0300: burp[150291] Previous backup is not a hardlinked_archive
2020-05-29 17:07:36 +0300: burp[150291]  will generate reverse deltas
2020-05-29 17:07:36 +0300: burp[150291] First keep value: 14, backup: 25 (25-1=24)
2020-05-29 17:07:36 +0300: burp[150291] New backup is not a hardlinked_archive (24%14=10)
2020-05-29 17:07:36 +0300: burp[150291] Doing the atomic data jiggle...
2020-05-29 17:07:36 +0300: burp[150291] skipping already present file: /home/dimti/passport/burp/main001/finishing/data/t/etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/9a478e8a35adb29f550ea70481e3c894/meta.json
2020-05-29 17:07:36 +0300: burp[150291] to save log space, skips of other already present files will not be logged
2020-05-29 17:07:42 +0300: burp[150291] could not find: /home/dimti/passport/burp/main001/finishing/currentdup/data/t/var/www/.../media/cache/images/7/4/5/2/1/8c13e4cbfa3050b52c30719833d3ae49f38.jpeg
2020-05-29 17:07:54 +0300: burp[150291] could not finish up backup.
2020-05-29 17:07:54 +0300: burp[150291] Problem with prior backup. Please check the client log on the server.2020-05-29 17:07:54 +0300: burp[150291] MESSAGE: Running notify script: main001  error in check_for_rubble()  backup 0 sendmail -t To: ..@...ru From: burp Subject: %b failed: %c %w Content-Type: text/plain; charset=utf-8
2020-05-29 17:07:54 +0300: burp[150291] /usr/share/burp/scripts/notify_script returned: 0
2020-05-29 17:07:54 +0300: burp[150291] exit child
```

Backup unable to finished, e.g. not founded file (maybe corrupted or deleted after fsck):
/media/cache/images/7/4/5/2/1/8c13e4cbfa3050b52c30719833d3ae49f38.jpeg

When trying latest unfinished backup (25) i fetcher error about as backup need to be finished.

If i tried delete previous backup (24) i got same message.

I see deletable backup - 16. If i try to delete this backup - its help?

![image](https://user-images.githubusercontent.com/582144/83272164-85039f80-a1d3-11ea-825a-f6e43de0b0b6.png)

**Comment by grke** [comment]
Hello,

No, it won't help to delete that one backup, because all the backups since then would have depended backup 24.

All my ideas from this point are destructive to some degree, so be really careful:

On the server:

Idea 1:
* Edit the manifests by hand in 0000025 so that it doesn't mention the file that it can't find. An entry for a file looks like this. It starts with a line starting with 't', and ends with a line starting with 'x':
```
t0021t/home/graham/testdir/zz/XR18.RPP
r003DgB oCW6 IGk B A A A Yao BAA DI BeBVui BbojJb Bb3sTK A A J A A
f0020/home/graham/testdir/zz/XR18.RPP
x0027100008:55fa69f68baae8af54f0d50d150f242c
````
* Try to run a backup again.
If you are lucky it was only that one file that had a problem, and the backup will complete.
If you are unlucky, there will be many more files that have a problem.

Idea 2:
* Move the 0000025 directory somewhere else outside the directory where all the other backups are, or delete 0000025.
* Delete the 'finishing' symlink that points to 0000025.
* Delete and recreate the 'current' symlink so that it points to 0000024. If you run 'ls -l', the symlink ought to look like the following. Note that it points directly to the directory. It is not an absolute path, and there is no trailing slash:
```
lrwxrwxrwx 1 root root   33 Mar 15 20:23 current -> 0000003 2020-03-15 10:23:43 +0000
```
* Try using the client to run a verify on 0000024: burp -a v -b 24
The problem is that if you are using hardlinked_archive=0, then backup 0000024 gets altered when shuffling files into backup 25 during the 'finishing' stage.
If you are lucky, it will be mostly OK, or maybe a few warnings.
If you are unlucky, it will be lots of warnings, or maybe completely broken.
You can try to run another backup, maybe it can successfully create a new one.

Idea 3:
* Find the most recent hardlinked backup. In your case, it looks like backup 17.
* Delete or move away all the backups since 17 (but don't move 17 itself). That is, move or delete 18 19 20 21 22 23 24 25. Check that there is a file in 0000017 called 'hardlinked'. This indicates that it is a hardlinked backup and you can delete all the backups that come after it. 
* Delete the 'finishing' symlink.
* Remove and recreate the 'current' symlink so that it points to backup 17.
* Verify backup 17.
* Try to run another backup.

Idea 4:
* Move everything aside and start again.

**Comment by dimti** [comment]
Usefull - first way, i search and delete warning-files in manifset

i probe revert to 015 backupset (previously before deletable and 15 backup also hardlinked backup) - verify and report me 8 warning). Then warning also stop used next backups and 16th new backup not shuffle completed. After remove warning files from manifest - backups is work. Thanks for helped me.
