### ISSUE TITLE
Auto upgrade for burp client Ubuntu

### ISSUE THREAD

**Issue by nhanvolac** [grke/burp#853]
Hello, 

I am having an issue when running an auto-upgrade function on the Ubuntu client (Debian).

By default, we have two files called "script" and "package", but when upgrading burp client on Ubuntu client (Debian), we must install more "burp-core", so I have to change the "burp-client "to "package" 
 and "burp-core" to package1, edit the "script" file, but the process is only to install "package".

That feature works well on CentOS because it only contains 1 file "burp-client".

I don't know if there is a solution to this issue, maybe installed more package to finned the process

Please help to point me in the right direction.

Thank you.

**Comment by grke** [comment]
Hello,

The autoupgrade feature only supports one 'script' and one 'package'.
I do not provide the debian packages, I only supply the source code for burp, which packagers do what they like with.

However, I can think of many ways to achieve your goal. Here is one idea:

Create a tar archive out of your two debian packages, so that you have a single 'package' file.
Update the 'script' file to unpack the tar file and install the two packages it contains.

:)
