### ISSUE TITLE
burp 2.2.18 fail test on arm64

### ISSUE THREAD

**Issue by kalos** [grke/burp#866]
Please, make more stable test for arm64.

Refer to this debian bugreport: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960321

Thanks!

**Comment by grke** [comment]
Hello,

I don't think that they should run those slow and intensive tests as part of their builds. These are more for myself to run before I do a burp release.
More appropriate would be to run the 'runner' unit tests.

I don't believe that I am able to change that, because I don't control the debian packaging scripts.
Do you know who controls the debian packaging scripts?

**Comment by kalos** [comment]
Hello,
Thanks for your quick reply.

I maintain the burp package for debian (and ubuntu). The tests scripts are in https://salsa.debian.org/debian/burp/-/tree/debian/debian/tests

I thought 'make test' was the right way to run full tests.
If you think it is superfluous I could replace 'burp-builtin-test' it with something like this:
burp-runner-test:
#!/bin/sh

exec 2>&1
autoreconf -vif
./configure --prefix=/usr --sysconfdir=/etc/burp --localstatedir=/var || exit 1
make runner
./runner

Do you think this is more appropriate?

**Comment by grke** [comment]
Hello,

That looks fine to me, assuming it works in debian's environment.
But the existing 'burp-unit-test' that you have also does the same thing, ie 'make check' runs 'runner'.

**Comment by kalos** [comment]
Well!
I just deleted "burp-builtin-test".

Sorry, I didn't realize that 'make check' invokes 'runner'.

Thank you so much!

**Comment by grke** [comment]
No worries, thanks for helping out.
