### ISSUE TITLE
Start on server boot

### ISSUE THREAD

**Issue by compumatter** [grke/burp#910]
Hello,

I have a few servers where for reasons I do not know, burp is not running.  On the suspect list is the client restarting the server and burp not running when it comes back online. 

What do you feel is the best procedure to insure burp is running at boot time of the server?

Thanks.

**Comment by grke** [comment]
Hello,

This is the responsibility of the distro that the server is using.

For example, I use debian, which is a distro that uses systemd.
You can tell systemd to start burp like any other daemon, and you can even tell it to listen on a socket and only start a server process when somebody connects to that socket.

You might also have a server that doesn't use systemd, in which case, maybe it uses init scripts. It may also be using something completely different.

Either way, this is a distro, or installation issue.
What to do depends upon the distro/installation, rather than the fact that the server is running burp.

**Comment by grke** [comment]
You can find example systemd files in the burp source in burp/systemd. These might help if your burp servers are being installed by hand.
